# If informative messages should be printed in the console (will clutter the log)
debug: false

# A populator is responsible for generating a small area of blocks, for example, ores in the ground.
#
# Vanilla values for ore generation can be found on the wiki: https://minecraft.gamepedia.com/Mineral_vein
# Most of the time, the values found there will produce the same results if plugged in here. But some might differ
# slightly (e.g. "tries" for emerald).
#
# POPULATOR FORMAT:
# - material: <block>                    # The type of block(s) to generate, or "all" for all blocks (only for replacing). (default: all)
#   type: [VEIN/SINGLE]                  # The populator/generation type: VEIN for clusters, SINGLE for solo blocks. (default: VEIN)
#   size: <vein size>                    # The size of the veins to generate. (default: 1)
#   tries: <generation tries per chunk>  # The number of generation attempts per chunk. (default: 0.0)
#   min-height: <min generation height>  # The min y-height to generate at.(default: 0)
#   max-height: <max generation height>  # The max y-height to generate at. (default: 255)
#   replace-with: <block>                # The type of block to replace previous instances of the specified material with, or "none" for no removal of previous blocks. (default: none)
#   replace-rest-with: <block>           # Type of block to replace all other blocks (not covered by the specified material) with, or "none" for no removal of other blocks. (default: none)
#   can-replace:                         # The type of blocks that can be replaced in the generation, or "all" for all. (default: stone, andesite, diorite, granite)
#     - <block>
#   worlds:                              # The worlds to generate in. (default: "world")
#     - <world name>
#   biomes: (all)                        # The biomes to generate in, or "all" for all biomes. (available: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html ) (default: all)
#     - <BIOME>
#
populators:
  - material: emerald_ore
    type: SINGLE
    tries: 4
    min-height: 4
    max-height: 31
    replace-with: stone
    biomes:
      - GRAVELLY_MOUNTAINS
      - MODIFIED_GRAVELLY_MOUNTAINS
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - WOODED_MOUNTAINS

  - material: diamond_ore
    size: 8
    tries: 1
    max-height: 15
    replace-with: stone





# -------------------- DEFAULT VALUES --------------------

# Default values used when absent from a populator above
default:
  material: all
  type: VEIN
  size: 1
  tries: 0.0
  min-height: 0
  max-height: 255
  replace-with: none
  replace-rest-with: none
  can-replace:
    - stone
    - andesite
    - diorite
    - granite
    - polished_andesite
    - polished_diorite
    - polished_granite
  worlds:
    - world
  biomes: all

