name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
api-version: 1.13
authors: [Gimme]
description: ${project.description}
load: STARTUP

commands:
  ores:
    description: All ores commands
    usage: "Unknown command. Type \"/ores help\" for help."
    permission: gimmeores.ores.*
  # TODO: remove
  #ores count:
  #  description: Count number of blocks of a specific type in surrounding chunks
  #  permission: gimmeores.*
  #  usage: "/ores <block> <chunk distance>"
  #ores load:
  #  description: Count number of blocks of a specific type in surrounding chunks
  #  permission: gimmeores.*
  #  usage: "/ores <block> <chunk distance>"

permissions:
  gimmeores.*:
    description: Wildcard permission
    default: op
    children:
      gimmeores.ores.*: true

  gimmeores.ores.*:
    description: Can use ores commands
    default: op
